### ISSUE TITLE
[Bug]: Crash when opening multiplayer

### ISSUE THREAD

**Issue by KCtops6** [TheIllusiveC4/CherishedWorlds#38] opened 2024-12-01 18:18 UTC
### Minecraft Version

1.20.1

### What happened?

The game crashes when going on the multiplayer menu.

### How do you trigger this bug?

1. Launch the Game
2. Click on Multiplayer.

### Loader

Forge

### Loader Version

Forge - 47.3.11

### API Version

N/A

### Mod Version

Cherished Worlds 1.20.1-6.1.6

### Relevant Log Outputs

https://gist.github.com/KCtops100/9221148434a296e18badd6353eab2a6a

**Comment by TheIllusiveC4** [comment] 2024-12-02 08:41
Duplicate of https://github.com/illusivesoulworks/cherishedworlds/issues/36

**Closed as not planned by TheIllusiveC4** 2024-12-02 08:41 UTC
Labels: type: bug, status: duplicate

**Comment by KCtops6** [comment] 2024-12-02 13:17
Thank you for your help.  I will reach out on that thread if further issues arise.
